---
.input-variables-mkdocs:
  - |
    print_input_parameters() {
      if [ -n "$2" ]; then
        printf "│ %-40s │ %-90s │\n" "$1" "$2"
      fi
    }
    echo ""
    echo -e "\033[1;33m===>\033[0m 💾 Print set inputs Variables"
    echo -e "┌──────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────┐"
    printf "│ %-40s │ %-90s │\n" "Variable" "Value"
    echo -e "├──────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────┤"
    print_input_parameters COMPONENT_VERSION_BUILD $COMPONENT_VERSION_BUILD
    echo -e "├──────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────┤"
    print_input_parameters CONTAINER_IMAGE_MKDOCS $CONTAINER_IMAGE_MKDOCS
    echo -e "└──────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘"
