---
.input-variables-mkdocs:
  - |
    echo ""
    echo -e "\033[1;33m===>\033[0m 💾 Print set inputs Variables"
    printf "┌ %-25s ┬ %-100s ┐\n" "─────────────────────────" "────────────────────────────────────────────────────────────────────────────────────────────────────"
    printf "| %-25s | %-100s |\n" "Variable" "Value"
    printf "├ %-25s ┼ %-100s ┤\n" "─────────────────────────" "────────────────────────────────────────────────────────────────────────────────────────────────────"
    printf "| %-25s | %-100s |\n" "CONTAINER_IMAGE_MKDOCS" "$CONTAINER_IMAGE_MKDOCS"
    printf "└ %-25s ┴ %-100s ┘\n" "─────────────────────────" "────────────────────────────────────────────────────────────────────────────────────────────────────"
